//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentss
    {
        public int student_id { get; set; }
        public string Namee { get; set; }
        public string birthdate { get; set; }
        public string gender { get; set; }
        public Nullable<int> grade { get; set; }
        public string course { get; set; }
    }
}
